services:
  - type: web
    name: calorie-calculator
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NPM_VERSION
        value: 9.0.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 